import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parsePlanMetadata } from './check-docs.mjs'

export const ROOT = resolve(fileURLToPath(import.meta.url), '..', '..')

const PLAN_FILE_PATTERN = /^(\d{4})-[a-z0-9-]+\.md$/

export function collectPlans(rootDirectory = ROOT) {
  const plans = []
  for (const [directory, inCompleted] of [
    ['active', false],
    ['completed', true],
  ]) {
    const absoluteDirectory = join(rootDirectory, 'docs', 'plans', directory)
    if (!existsSync(absoluteDirectory)) continue
    for (const entry of readdirSync(absoluteDirectory, { withFileTypes: true })) {
      const match = entry.isFile() ? PLAN_FILE_PATTERN.exec(entry.name) : null
      if (match === null) continue
      const content = readFileSync(join(absoluteDirectory, entry.name), 'utf8')
      const metadata = parsePlanMetadata(content)
      plans.push({
        number: Number(match[1]),
        directory,
        fileName: entry.name,
        title: content.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? entry.name,
        status: metadata.status ?? (inCompleted ? 'Unknown' : 'Active'),
        completed: metadata.completed,
        supersedes: metadata.supersedes,
        supersededBy: metadata['superseded-by'],
      })
    }
  }
  return plans.sort((left, right) => left.number - right.number)
}

function relationship(plan) {
  const parts = []
  if (plan.supersedes !== undefined) parts.push(`Supersedes ${plan.supersedes}`)
  if (plan.supersededBy !== undefined) parts.push(`Superseded by ${plan.supersededBy}`)
  return parts.length === 0 ? '—' : parts.join('; ')
}

export function generatePlanIndex(plans) {
  const rows = plans.map(
    (plan) =>
      `| [${String(plan.number).padStart(4, '0')}](${plan.directory}/${plan.fileName}) | ${plan.title} | ${plan.status} | ${plan.completed ?? '—'} | ${relationship(plan)} |`,
  )
  return [
    '# Implementation Plans',
    '',
    'Implementation plans are historical records of a task as it was planned and completed. Their naming, metadata, and lifecycle conventions are defined in `AGENTS.md` §8, and `npm run check:docs` validates them. Completed plans may contain facts from the time they were written; the live documents own current behavior.',
    '',
    'This index is generated by `npm run plan:index`.',
    '',
    '| Plan | Title | Status | Completed | Supersedes |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n')
}

function main() {
  const content = generatePlanIndex(collectPlans())
  if (process.argv.includes('--write')) {
    writeFileSync(resolve(ROOT, 'docs', 'plans', 'README.md'), content)
    console.log('Wrote docs/plans/README.md.')
    return
  }
  process.stdout.write(content)
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main()
}
